### PR TITLE
Added market_hash_name field

### PR DESCRIPTION
**Pull request by Yashko**
Faced a problem where i need to get item names as in market. The 'name' field will return only skin name, without exterior. So i need to do it on my own, and check if there is exterior, because it can be a sticker. And steam have market_hash_name field, so would be nice to have it.

### CODE REVIEW

**Comment by danielhusar** [comment]
Thanks! Can you please rename it to be camelCase to keep consistency?

**Comment by Yashko** [comment]
done

**Comment by Yashko** [comment]
@danielhusar

**Comment by danielhusar** [comment]
Thanks!

**Comment by danielhusar** [comment]
available in 4.2.0

**Pull request merged**
